---
title: "Assignment 4: Network Analysis"
author: "Jennifer Horowitz"
date: "10/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```


## Load Libraries

```{r}
library(osmdata)
library(opentripplanner)
library(tidyverse)
library(sf)
library(ggthemes)
library(ggspatial)
#library(raster)
```

## Load Apartment Rentals

```{r load library locations}
apartmentrentals <- st_read(
  "https://data.cambridgema.gov/api/geospatial/iect-ma2e?method=export&format=KML")
```


```{r}
MA_state_plane <- "+proj=lcc +lat_1=41.71666666666667 +lat_2=42.68333333333333 +lat_0=41 +lon_0=-71.5 +x_0=200000 +y_0=750000 +ellps=GRS80 +units=m +no_defs"
```







```{r}
# opq(bbox = 'Cambridge MA USA') %>%
# add_osm_feature(key = 'highway') %>%
# osmdata_xml(file = 'OTP/graphs/default/cambridge_streets.osm')

```


```{r}
cambridge_street_features <- opq(bbox = 'Cambridge MA USA') %>%
  add_osm_feature(key = 'highway') %>%
  osmdata_sf()

cambridge_streets <- cambridge_street_features$osm_lines %>%
  st_transform(crs = MA_state_plane)
```


```{r}
##path_otp <- otp_dl_jar("OTP")
```

```{r, message=FALSE, results='hide', warning = FALSE}
path_data <- file.path(getwd(), "OTP")
path_otp <- paste(path_data, "otp.jar",sep = "/")
otp_build_graph(otp = path_otp, dir = path_data, memory = 1024) 
```


```{r}
otp_setup(otp = path_otp, dir = path_data, memory =12024)
# Connect to opentripplanner
otpcon <- otp_connect()
```


## Create Isochromes

Apartment rentals within a 10min walkshed.

```{r warning = F}

first50points <- apartmentrentals %>%
  head(50)

iso_10min_walk <- otp_isochrone(otpcon = otpcon,
                                fromPlace = first50points,
                                mode = "WALK",
                                cutoffSec = 600,
                                ncores = 6
                                ) %>%
  st_transform(crs = MA_state_plane) %>%
  mutate(mode = "walk")

iso_10min_drive <-
  otp_isochrone(otpcon = otpcon,
                fromPlace = first50points,
                mode = "CAR",
                cutoffSec = 600,
                ncores = 6
                ) %>%
  st_transform(crs = MA_state_plane) %>%
  mutate(mode = "drive")

iso_all_modes <- rbind(iso_10min_drive, iso_10min_walk)

iso_15min_walk <- otp_isochrone(otpcon = otpcon,
                                fromPlace = first50points,
                                mode = "WALK",
                                cutoffSec = 900,
                                ncores = 6
                                ) %>%
  st_transform(crs = MA_state_plane) %>%
  mutate(mode = "walk")

iso_15min_drive <-
  otp_isochrone(otpcon = otpcon,
                fromPlace = first50points,
                mode = "CAR",
                cutoffSec = 900,
                ncores = 6
                ) %>%
  st_transform(crs = MA_state_plane) %>%
  mutate(mode = "drive")


iso_all_modes_15 <- rbind(iso_15min_drive, iso_15min_walk)

iso_5min_bike <- otp_isochrone(otpcon = otpcon,
                                fromPlace = first50points,
                                mode = "BICYCLE",
                                cutoffSec = 300,
                                ncores = 6
                                ) %>%
  st_transform(crs = MA_state_plane) %>%
  mutate(mode = "Bike")

iso_5min_drive <-
  otp_isochrone(otpcon = otpcon,
                fromPlace = first50points,
                mode = "CAR",
                cutoffSec = 300,
                ncores = 6
                ) %>%
  st_transform(crs = MA_state_plane) %>%
  mutate(mode = "drive")

iso_all_modes3 <- rbind(iso_5min_drive, iso_5min_bike)

otp_stop()
```

## Draw the Isochromes on the map



```{r}
right_side <- st_bbox(iso_all_modes)$xmax
left_side  <- st_bbox(iso_all_modes)$xmin
top_side <- st_bbox(iso_all_modes)$ymax
bottom_side <- st_bbox(iso_all_modes)$ymin
ggplot(iso_all_modes) +
  annotation_map_tile(zoomin = 0, progress = "none") +
  geom_sf(aes(fill = mode), alpha = 0.5) +
  geom_sf(data = first50points) +
  coord_sf(xlim = c(left_side, right_side), 
           ylim = c(bottom_side, top_side), expand = FALSE) +
  scale_fill_viridis_d(name = "Area that is reachable within 10 minutes",
                       labels = c("By car", "By foot")) +
  theme_map() +
  labs(caption = "Basemap Copyright OpenStreetMap contributors")
```


```{r}
right_side <- st_bbox(iso_all_modes)$xmax
left_side  <- st_bbox(iso_all_modes)$xmin
top_side <- st_bbox(iso_all_modes)$ymax
bottom_side <- st_bbox(iso_all_modes)$ymin
ggplot(iso_all_modes) +
  annotation_map_tile(zoomin = 0, type = "stamenbw", progress = "none") +
  geom_sf(aes(fill = mode), alpha = 0.5) +
  geom_sf(data = first50points) +
  coord_sf(xlim = c(left_side, right_side), 
           ylim = c(bottom_side, top_side), expand = FALSE) +
  scale_fill_viridis_d(name = "Area that is reachable within 10 minutes",
                       labels = c("By car", "By foot")) +
  theme_map() +
  labs(caption = "Basemap Copyright OpenStreetMap contributors")
```


### Number of Apartments within 10min walk/drive

```{r}
iso_areas <- iso_all_modes %>%
  mutate(area = st_area(iso_all_modes)) %>%
  st_set_geometry(NULL) %>%
  pivot_wider(names_from = mode, values_from = area) 

ggplot(iso_areas, 
       aes(x = as.numeric(walk), y = as.numeric(drive))) +
  geom_point() +
  scale_x_continuous(name = 
            "Area within a tenfive-minute walking distance\nof an apartment rentat\n(square m)") +

  scale_y_continuous(name = 
            "Area within a ten-minute driving distance\nof a apartment rental\n(square m)") +

  theme_bw()
```

### Number of Apartments within 15min walk/drive



```{r}
iso_areas <- iso_all_modes_15 %>%
  mutate(area = st_area(iso_all_modes_15)) %>%
  st_set_geometry(NULL) %>%
  pivot_wider(names_from = mode, values_from = area) 

ggplot(iso_areas, 
       aes(x = as.numeric(walk), y = as.numeric(drive))) +
  geom_point() +
  scale_x_continuous(name = 
            "Area within a fifteen-minute walking distance\nof an apartment rentat\n(square m)") +

  scale_y_continuous(name = 
            "Area within a fifteen-minute driving distance\nof a apartment rental\n(square m)") +

  theme_bw()
```

### Number of Apartments within a 5min bike/drive

```{r}
iso_areas3 <- iso_all_modes3 %>%
  mutate(area = st_area(iso_all_modes3)) %>%
  st_set_geometry(NULL) %>%
  pivot_wider(names_from = mode, values_from = area) 

ggplot(iso_areas3, 
       aes(x = as.numeric(Bike), y = as.numeric(drive))) +
  geom_point() +
  scale_x_continuous(name = 
            "Area within a five-minute biking distance\nof an apartment rental\n(square m)") +

  scale_y_continuous(name = 
            "Area within a five-minute driving distance\nof a apartment rental\n(square m)") +

  theme_classic()
```

